### ISSUE TITLE
File location and GUI visualisation

### ISSUE THREAD

**Issue by rpelicae** [hallamlab/metapathways2#42]
Hello,

I'm using MP 2.5 on a mac. I've installed the software using the .dmg disk image. I'm firing MP, using the GUI, on some metagenomic reads with default parameters (as in the documentation) and watching single-sample results on the result tab. Until the 'Number of hits from db's (I'm using bacterial all.faa from NCBI's RefSeq, Metacyc, COG and CAZY that you provided) I can see which LAST output file the GUI visualises but then it gets blurry.

-Which file is parsed to show "Annotations meeting user defined threshold from 'databases' " in the GUI?

-I assume these annotated proteins above threshold are the ones that should be visible in the separate functional hierarchies tabs, but the numbers don't add up?

-The /blast_results/.LASTout.parsed .txt files are used to create the /genbank/annot.gff file. In the .gff file: 'source_db', I only have 'none' for hypothetical proteins that had no LAST hit or 'all.faa', hits from my Refseq db. Metacyc, COG and CAZY hits are not parsed. So I only have RefSeq annotations in my /ptools/0.pf file although I can see the hits from the other databases in /results/annotation_table/orf_annotation_table.txt.
Does this has to do with Functional Annotation parameters and if so how to tweak them? I have tried some changes (BSR, e-value) but only with minor changes. Furthermore these changes only occur in the 
orf_annotation_table.txt file and not in the /genbank/annot.gff file which is used for Pathway Tools.

Kind regards,
Rudy

**Comment by kishori82** [comment]
Hi Rudy
In the FAQ section of the wiki for MetaPathways I added Question 12, which  discusses  the annotation process, in the pipeline,. Let me know if you have more questions. The writing needs  some polishing, I just added it yesterday.

https://github.com/hallamlab/metapathways2/
Regards,
Kishori
Thanks

**Comment by rpelicae** [comment]
Hello, thanks for the reply.

I had a closer look to the FAQ and Question 12.

-In Question 12; Annotate ORF's. There's a typo, ORF3 should be considered as a hypothetical protein, not ORF 2, also there are some inconsistencies between the table and the text (enzyme S, enzyme Y; enzyme Z in the table ..)

-I understand you use a conservative approach when comparing database hits but what are your criteria for 'almost similar' annotations? Different db's have differing policies in functional names, etc.. maybe it would be nice if the user could decide which annotation to pick and not just drop these annotations and consider it as being a hypothetical protein?

-In the GUI: the 'Number of hits from database' is represented by /blast_results/LASTout.parsed.txt and not /LASTout as said in Question 12. Thus 'Number of annotations meeting defined threshold from database' is represented by the annotations in the ORF_annotation_table.txt file, that represents the 'Total Protein annotations'. 
Thus relating to Question 12, all these annotations should be present in the different functional hierarchy tabs (COG, MetaCyc, ...) because they passed the threshold and were consistently annotated, but for COG this is not the case and in the MetaCyc tab nothing is shown. 
Additionally you indicate that if the annotations are almost similar they are 'stitched' together to form one annotation, so each ORF should have one 'stitched' annotation from different databases in the end and the original annotations from each database could be shown in each separate tab?

- I still have the feeling that annotations reported in the /genbank/.annot.gff file are somewhat biased towards RefSeq hits ('sourcedb'). Related to this, what does 'annotvalue' mean? I'm interested in the MetaCyc annotations because I would very much like to use MP to provide an ePGDB that can be explored in Pathway Tools, which is based on MetaCyc database to create the ePGDB.

Kind regards,
Rudy

**Comment by nielshanson** [comment]
Hi Rudy,

Thanks for your question as I'm sure others are wondering as well. Sorry for the late reply as I was in the final stages of writing my dissertation.

After looking over the code closely with Kishori, I think we can clear-up some of this confusion. I've rewritten most of FAQ Question 12 to reflect this, but I'll repeat the just of it here. First things first, at no point does MetaPathways create synthetic annotations for ORFs by combining hits from multiple databases. We did at one time years ago play with this idea, as it could be used to predict more MetaCyc pathways in Pathway Tools. However, its very difficult to rationalize from  from a methods point of view so we dropped it years ago.

However, you should note that MetaPathways takes three perspectives on annotation: (1) minimum alignment quality, (2) annotation against individual databases, and (3) annotation against for pathway prediction in Pathway Tools which takes into consideration hits from multiple databases.

First, all annotations regardless of database have to meet certain alignment quality scores which is what is described in the FAQ example. Our default thresholds are (Length: 180bp reads, 60 aa ORFs, E-value: 1e-6, Score: 20, and BSR: 0.4). 

Next, we are interested in how these ORFs annotate against individual databases. As you mentioned, each specialized database is annotated in a particular way and often is placed in the context of a functional hierarchy, which is the case for COG, KEGG, or SEED. MetaCyc is the exception here, because these counts are extracted from predicted pathways of the ePGDB, but I'll return to this point later.

Finally, we would like to create a set of annotations for each sample to predict pathways in Pathway Tools, and here we look at annotations across databases. PathoLogic, the pathway prediction algorithm in Pathway Tools processes annotations based on two criteria: E.C. numbers and key words, so we would like annotations ideally have E.C. numbers and are highly descriptive. Here we introduced an 'information-score' that counts the number of words (after uninformative stop words and 'protein' and 'enzyme' are removed) with a +10 score for the presence of an E.C. number. ORFs that have hits from multiple databases will select the annotation that maximizes this score. What we have noticed empirically from processing hundreds of metagenomes is that ORFs often map to similar enzymes across databases, so this score effectively selects the most specific one which really helps since MetaCyc has many different pathway variants to choose from. It also, as you suggested, biases us to RefSeq annotations as often those in our experience are the best annotated with EC numbers, and so gives RefSeq annotations the advantage over other databases in terms of information-score. The annotations that win in terms of information are those that end up in the 'product' field of the large functional_annotation table in the GUI.

Going back to the MetaCyc table. It is empty because these are filled with the annotations that were mapped to MetaCyc pathways via PathoLogic. The are extracted from the ePGDB after it is created. So an ePGDB has to be built and a pathway predicted before ORF counts in this table. This is one of the last steps of the MetaPathways pipeline and can take a while in some cases (Pathway Tools can use a lot of memory here 8-16GB). So the MetaCyc table is empty because either the ePGDB has not been created yet or the parsing script failed. I'd be interested in which is was, because generally I find this part of the code pretty stable.

Just a tip on creating ePGDBs, the MetaCyc database that is provided is only the subset of Uniprot IDs that are found in Pathway Tools. So although you can use this to predict pathways, I suspect you'll do a more comprehensive job if you use RefSeq as well. There are many proteins in RefSeq that will map to MetaCyc reactions by keywords or E.C. number that are not contained in the MetaCyc database.

Let me know if you have any more questions or if something wasn't clear.

Sincerely,
Niels
