### ISSUE TITLE
The bundled metacyc-v5-2011-10-21 does not seem to 'work'

### ISSUE THREAD

**Issue by gwilymh** [hallamlab/metapathways2#77]
I am running MetaPatways 2.5 in OS 10.6.8.  Although my analyses consistently return functional categories for the SEED, CAZY and COG databases, for some reason no annotations are produced for the MetaCyc database. I.e. the ORF count is 0 for each Pathway/Reaction. I am using the metaCyc database that was bundled with the program, metacyc-v5-2011-10-21.

**Comment by gwilymh** [comment]
NB: I am selecting metacyc-v5-2011-10-21 from the Functional Annotation Parameters menu under Parameters.

**Comment by ariahahn** [comment]
Are you building pgdbs? The metacyc page in the GUI is different in that it
actually displays pathways not annotations directly from the database like
the other pages. In order to have annotations you must have successfully
built a pathway genome database with pathway tools (one the final stages in
MP 2.5). If yes, are there any errors?

Aria

**Comment by gwilymh** [comment]
I don't think I was. That could well be the problem. I will run it now and see how it goes.

**Comment by gwilymh** [comment]
I have run an analysis on fasta file, selecting the metacyc-v5-2011-10-21 database and the ePGDB option. Metapathways ran to completion. While running, some gene pathway maps popped up on the screen. There were still no MetaCyc results under the results tab, or any errors in the log file that I could link with a lack of MetaCyc annotations. Any suggestions?

**Comment by hallamlab** [comment]
MetaCyc results only appear if a ePGDB was built - we are releasing a new version shortly that should help with these issues
